name: Handle Issues
description: 'Handle Issues'

inputs:
    outcome:
        description: "Result from the Task"
        required: true
    label:
        description: "Issue Label"
        required: true
    title:
        description: "Issue Title"
        required: true

runs:
    using: "composite"
    steps:
        - name: if task Fail create an issue or comment on the issue
          if: ${{ inputs.outcome == 'failure' }}
          uses: actions/github-script@v6
          with:
            script: |
                console.log("Failure...")
        - name: close issue when outcome is successfully
          if: ${{ inputs.outcome == 'success' }}
          uses: actions/github-script@v7
          with:
            script: |
                console.log(${{ inputs.label}})
                
